### ISSUE TITLE
`asap-data` | OpenEye Toolkits version 2024.2.3 breaks on lilac

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#1010]
Not *currently* an issue, but may become so soon, which is that our GLIBC version on Lilac is not up to date enough to handle the newest OE versions.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/__init__.py", line 142, in __getattr__
    obj = self._find_attr(name)
  File "/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/__init__.py", line 132, in _find_attr
    return self._get_openeye_module(name)
  File "/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/__init__.py", line 108, in _get_openeye_module
    spec.loader.exec_module(mod)
  File "/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/oespruce.py", line 47, in <module>
    _oespruce = swig_import_helper()
  File "/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/oespruce.py", line 44, in swig_import_helper
    _oespruce = libs.OEGetModule('_oespruce1533')
  File "/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/libs/__init__.py", line 109, in OEGetModule
    mod = importlib.util.module_from_spec(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/openeye/libs/python3-linux-x64-g++10.x/liboespruce-1.5.3.3.so)
```

**Comment by hmacdope** [comment]
Idk why they didn't statically link it, but this is a bit of a problem, AFAIK we can't really work around old GLIBC.

**Comment by hmacdope** [comment]
Without updating lilac system libs itself.

**Comment by mikemhenry** [comment]
Yah an older version of openeye toolkits will be needed (we could ask them to statically link it, they might not like the larger binary).

I know you can install  `sysroot_linux-64=2.28`, that _might_ work, but only if tha glibc gets picked up before the one that is on lilac

**Comment by hmacdope** [comment]
We can just add a pin, I don't think we will lose a lot.
