### ISSUE TITLE
Fragalysis download currently encountering a server error

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#252]
```
(ad-3.9) ?1 /Users/alexpayne/Scientific_Projects/covid-moonshot-ml % download-fragalysis-data -o /Users/alexpayne/Downloads/test_fragalysis

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>

Traceback (most recent call last):
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/bin/download-fragalysis-data", line 8, in <module>
    sys.exit(main())
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-data/asapdiscovery/data/scripts/download_fragalysis_data.py", line 20, in main
    download(args.o, args.x)
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-data/asapdiscovery/data/fragalysis.py", line 47, in download
    url_dl = r.text.split(':"')[1].strip('"}')
IndexError: list index out of range
```

**Comment by apayne97** [comment]
I think we just need to change the API call to match the new format:
```
post params:
- target_name: Selected target
- proteins: Comma separated list of protein codes within target e.g. "Mpro-6lu7_2C,Mpro-6m0k_0A".
If left blank the whole target will be scanned.
- pdb_info: True/False - include pdb file
- bound_info: True/False - include bound file (if available)
- cif_info: True/False - include cif file (if available)
- mtz_info: True/False - include mtz file (if available)
- diff_info: True/False - include diff file (if available)
- event_info: True/False - include event file (if available)
- sigmaa_info: True/False - include sigmaa file (if available)
- sdf_info: True/False - include molecule sdf file (if available)
- single_sdf_file: True/False - Also combine molecule sdf files into single file (if available)
- trans_matrix_info: True/False - include transformation file (if available)
- metadata_info: True/False - include metadata csv file for whole target set
- smiles_info: True/False - include csv file containing smiles for attached molecules
- static_link: True/False - whether zip contents will be saved as a time dependent snapshot
- file_url: Get link to static file (this will reconstruct the zip file if it has been cleaned up.post params:
- target_name: Selected target
- proteins: Comma separated list of protein codes within target e.g. "Mpro-6lu7_2C,Mpro-6m0k_0A".
If left blank the whole target will be scanned.
- pdb_info: True/False - include pdb file
- bound_info: True/False - include bound file (if available)
- cif_info: True/False - include cif file (if available)
- mtz_info: True/False - include mtz file (if available)
- diff_info: True/False - include diff file (if available)
- event_info: True/False - include event file (if available)
- sigmaa_info: True/False - include sigmaa file (if available)
- sdf_info: True/False - include molecule sdf file (if available)
- single_sdf_file: True/False - Also combine molecule sdf files into single file (if available)
- trans_matrix_info: True/False - include transformation file (if available)
- metadata_info: True/False - include metadata csv file for whole target set
- smiles_info: True/False - include csv file containing smiles for attached molecules
- static_link: True/False - whether zip contents will be saved as a time dependent snapshot
- file_url: Get link to static file (this will reconstruct the zip file if it has been cleaned up.
```

**Comment by kaminow** [comment]
I just checked and these are the same parameters we're currently using, so we might need to reach out to the DLS folks

**Comment by kaminow** [comment]
the code in #255 resolves this I think (at least on my machine)
