### ISSUE TITLE
mtenn bug breaks end2end workflow

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#485]
currently running the end2end docking workflow on an `mtenn`-enabled structure results in:
```
2023-09-26 03:51:39,581 | single_target_docking | INFO | dock_small_scale_end_to_end.py | main | Using GAT model: asapdiscovery-SARS-CoV-2-Mpro-GAT-2023.08.25
Traceback (most recent call last):
  File "/home/sheen/miniconda3/envs/asapdiscovery/bin/dock-small-scale-e2e", line 8, in <module>
    sys.exit(main())
  File "/lila/home/sheen/asapdiscovery/asapdiscovery-docking/asapdiscovery/docking/scripts/dock_small_scale_end_to_end.py", line 636, in main
    None if args.no_schnet else SchnetInference.from_latest_by_target(args.target)
  File "/lila/home/sheen/asapdiscovery/asapdiscovery-ml/asapdiscovery/ml/inference/inference.py", line 66, in from_latest_by_target
    return cls.from_ml_model_spec(model_spec, **kwargs)
  File "/lila/home/sheen/asapdiscovery/asapdiscovery-ml/asapdiscovery/ml/inference/inference.py", line 108, in from_ml_model_spec
    return cls.from_local_model_spec(
  File "/lila/home/sheen/asapdiscovery/asapdiscovery-ml/asapdiscovery/ml/inference/inference.py", line 136, in from_local_model_spec
    model = build_model(
  File "/lila/home/sheen/asapdiscovery/asapdiscovery-ml/asapdiscovery/ml/utils.py", line 297, in build_model
    pred_readout = mtenn.model.PIC50Readout(substrate=substrate, Km=km)
TypeError: PIC50Readout.__init__() got an unexpected keyword argument 'substrate'
2023-09-26 03:51:39,668 - distributed.deploy.adaptive_core - INFO - Adaptive stop
2023-09-26 03:51:40,073 - distributed.deploy.adaptive_core - INFO - Adaptive stop
```

**Comment by kaminow** [comment]
Unfortunately I won’t be in front of my computer until late tomorrow EST, but I think you just need to update your mtenn version to 0.3.0. Alternatively, I think you can check the models yaml file and manually select one that was trained before mtenn 0.3.

**Comment by hmacdope** [comment]
Closing as Mtenn version mismatch, #532 addressed should make this clearer.
