### ISSUE TITLE
add type hints to OE loading and saving functions

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#603]
to avoid the horror of C++ error messages (courtesy of @JenkeScheen):
```
complex = load_openeye_design_unit("MERS_x0213_ASAP-0010752-001_monomer.oedu")

save_openeye_pdb(complex, pdb_fn="out.pdb")`
```

```
Traceback (most recent call last):
  File "/Users/jenkescheen/projects/mers/mers_retro_p1p_nov_23/setup/02_setup/monomer/prepped/prepped_structure_cache/oedu_to_pdb.py", line 6, in <module>
    save_openeye_pdb(complex, pdb_fn="out.pdb")
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-data/asapdiscovery/data/openeye.py", line 416, in save_openeye_pdb
    oechem.OEWriteMolecule(ofs, mol)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/openeye/oechem.py", line 27509, in OEWriteMolecule
    return _oechem.OEWriteMolecule(*args)
TypeError: Wrong number or type of arguments for overloaded function 'OEWriteMolecule'.
  Possible C/C++ prototypes are:
    OEChem::OEWriteMolecule(OEChem::oemolostream &,OEChem::OEMCMolBase &)
    OEChem::OEWriteMolecule(OEChem::oemolostream &,OEChem::OEQMolBase &)
    OEChem::OEWriteMolecule(OEChem::oemolostream &,OEChem::OEMolBase &)
    OEChem::OEWriteMolecule(OEChem::oemolostream &,OEChem::OEMol &)
    OEChem::OEWriteMolecule(OEChem::oemolostream &,OEChem::OEQMol &)
    OEChem::OEWriteMolecule(OEChem::oemolostream &,OEChem::OEGraphMol &)
    OEChem::OEWriteMolecule(OEChem::oemolothread &,OEChem::OEMolBase &)
    OEChem::OEWriteMolecule(OEChem::oemolothread &,OEChem::OEMCMolBase &)
    OEChem::OEWriteMolecule(OEChem::oemolothread &,OEChem::OEQMolBase &)
```

**Comment by hmacdope** [comment]
See also #544
