### ISSUE TITLE
CLI might be broken

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#741]
currently on main running `asap-cli --help` returns:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/bin/asap-cli", line 5, in <module>
    from asapdiscovery.cli.cli import cli
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-cli/asapdiscovery/cli/cli.py", line 9, in <module>
    from asapdiscovery.docking.cli import docking  # noqa: F401, E402, F811
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-docking/asapdiscovery/docking/cli.py", line 4, in <module>
    from asapdiscovery.cli.cli_args import (
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-cli/asapdiscovery/cli/cli_args.py", line 4, in <module>
    from asapdiscovery.ml.models import ASAPMLModelRegistry
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-ml/asapdiscovery/ml/models.py", line 11, in <module>
    from mtenn.config import ModelType
ModuleNotFoundError: No module named 'mtenn.config'
```

**Comment by hmacdope** [comment]
Ill fix this ASAP.

**Comment by hmacdope** [comment]
Ah apologies @JenkeScheen , I was trying to think how we could have missed this, but it is an environment versioning issue (need `mtenn>=0.5`). 

Running the following (yay new `mtenn` conda-forge) in your active environment should fix this:

```
mamba install mtenn=0.5 -c conda-forge 
```

**Comment by JenkeScheen** [comment]
ah - I must have missed that this got pinned. Cheers!
