### ISSUE TITLE
`asap-alchemy gather` seems broken

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/asapdiscovery#756]
on current `main`:
```
$ asap-alchemy gather
Connecting to Alchemiscale...
AlchemicalNetwork-08f7e9c21af9033b526e1774785758c3-asap-public-evd68_p1_large_1                                                         
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ status                                                                        ┃                                                count ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ complete                                                                      │                                                  433 │
│ running                                                                       │                                                    0 │
│ waiting                                                                       │                                                    0 │
│ error                                                                         │                                                   35 │
│ invalid                                                                       │                                                    0 │
│ deleted                                                                       │                                                    0 │
└───────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────────────────────┘
Gathering network results from Alchemiscale instance: https://api.alchemiscale.org with key AlchemicalNetwork-08f7e9c21af9033b526e1774785758c3-asap-public-evd68_p1_large_1
⣻ ⣻ Retrieving Transformation results ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0/156 -:--:--
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 42, in _get_transformation_results
    return tf_sk, client.get_transformation_results(tf_sk, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 1073, in get_transformation_results
    tf: Transformation = self.get_transformation(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 329, in get_transformation
    tf = json_to_gufe(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 27, in json_to_gufe
    return GufeTokenizable.from_dict(json.loads(jsondata, cls=JSON_HANDLER.decoder))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/bin/asap-alchemy", line 8, in <module>
    sys.exit(alchemy())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py", line 282, in gather
    network_with_results = client.collect_results(planned_network=planned_network)
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py", line 167, in collect_results
    for tf_sk, raw_result in self._client.get_network_results(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 995, in get_network_results
    return self._get_network_results(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 947, in _get_network_results
    tf_sk, result = future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asapdiscovery/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: the JSON object must be str, bytes or bytearray, not list
```
[planned_network.json](https://github.com/choderalab/asapdiscovery/files/14027329/planned_network.json)

**Comment by JenkeScheen** [comment]
@dotsdl we think this may be an issue stemming from an update to `alchemiscale` server-side, are you able to point us in the right direction?

**Comment by dotsdl** [comment]
Diving into this now!

**Comment by dotsdl** [comment]
Apologies, I believe this is due to my failure to merge the new 0.3.0 release PR for the `conda-forge` `alchemiscale` feedstock: https://github.com/conda-forge/alchemiscale-feedstock/pull/6

Once the 0.3.0 packages are up [here](https://anaconda.org/conda-forge/alchemiscale-client/files), then `gather` should work again as before for `asap-alchemy`.

**Comment by dotsdl** [comment]
I've updated the `alchemiscale` [release checklist](https://github.com/openforcefield/alchemiscale/wiki/Release-Checklist) to include the `conda-forge` feedstock update so we avoid this problem in the future, though there is a always some time delay between release, deployment, and `conda-forge` package builds.

**Comment by dotsdl** [comment]
@JenkeScheen please update your conda env with the latest `alchemiscale-client` package; `gather` should work again once you've done this.

**Comment by JenkeScheen** [comment]
worked a treat, thank you @dotsdl !
