### ISSUE TITLE
`asap-docking` Missing docking result causes a bug

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#989]
I think I've found the bug, but we need a solution.

Appending `None` to this list of docking results here:
https://github.com/choderalab/asapdiscovery/blob/9f73bb2d99b60176a7b7ff754aa08fc78bdb40e9/asapdiscovery-docking/asapdiscovery/docking/openeye.py#L336

causes an error here in `small_scale` and `cross_docking`
https://github.com/choderalab/asapdiscovery/blob/9f73bb2d99b60176a7b7ff754aa08fc78bdb40e9/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py#L224-L228

https://github.com/choderalab/asapdiscovery/blob/9f73bb2d99b60176a7b7ff754aa08fc78bdb40e9/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/small_scale_docking.py#L323-L327

and I haven't tested it but I think it should cause an error in `large_scale_docking` here:
https://github.com/choderalab/asapdiscovery/blob/9f73bb2d99b60176a7b7ff754aa08fc78bdb40e9/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/large_scale_docking.py#L286-L293

here's my error:
```
Traceback (most recent call last):
  File "/home/paynea/miniforge3/envs/asapdiscovery/bin/asap-docking", line 8, in <module>
    sys.exit(docking())
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py", line 273, in cross_docking
    cross_docking_workflow(inputs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 227, in cross_docking_workflow
    output_dir / "docking_results.sdf", [r.posed_ligand for r in results]
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 227, in <listcomp>
    output_dir / "docking_results.sdf", [r.posed_ligand for r in results]
AttributeError: 'NoneType' object has no attribute 'posed_ligand'
```

**Comment by hmacdope** [comment]
Can't we just place responsibility on callee 

```python
    output_dir / "docking_results.sdf", [r.posed_ligand for r in results]
```

will just become 

```

```python
    output_dir / "docking_results.sdf", [r.posed_ligand for r in results if r is not None]
```

**Comment by hmacdope** [comment]
I am fairly sure sure that None is returned to make sure that it is clear a docking run failed in the resulting dataframes.

**Comment by apayne97** [comment]
> I am fairly sure sure that None is returned to make sure that it is clear a docking run failed in the resulting dataframes.

I'll make that simple fix now, but this isn't right, because we make the results dataframes with a scorer, which has this:
https://github.com/choderalab/asapdiscovery/blob/ec29a7b94594e45db0ae87cd542e3beb6f04d505/asapdiscovery-docking/asapdiscovery/docking/scorer.py#L302-L319

Which will immediately fail if the input is None

**Comment by hmacdope** [comment]
This is fixed now.
