### ISSUE TITLE
`asap-docking` Another bug hunt

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#990]
here's the error:
```
Traceback (most recent call last):
  File "/home/paynea/miniforge3/envs/asapdiscovery/bin/asap-docking", line 8, in <module>
    sys.exit(docking())
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py", line 269, in cross_docking
    cross_docking_workflow(inputs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 149, in cross_docking_workflow
    prepped_complexes = prepper.prep(
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py", line 127, in prep
    inputs, cached_outputs = ProteinPrepperBase._gather_new_tasks(
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py", line 76, in _gather_new_tasks
    cached_outputs = [
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py", line 79, in <listcomp>
    if inp.hash in cached_by_hash
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-data/asapdiscovery/data/schema/complex.py", line 101, in hash
    return f"{self.target.hash}+{self.ligand.fixed_inchikey}"
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-data/asapdiscovery/data/schema/ligand.py", line 380, in fixed_inchikey
    mol = self.to_oemol()
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-data/asapdiscovery/data/schema/ligand.py", line 260, in to_oemol
    mol = set_SD_data(mol, data)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-data/asapdiscovery/data/backend/openeye.py", line 856, in set_SD_data
    raise TypeError(
TypeError: Expected an OpenEye OEMol, OEGraphMol, or OEConf, but got <class 'NoneType'>
```

**Comment by apayne97** [comment]
I made a gist to demonstrate where the problem arises - in #692 by changing the `sdf_string_to_oemol` function, I (accidentally) made it so that `to_oemol()` returns None instead of returning an OEGraphMol if the ligand is empty.

If we like returning an empty `OEMol` I can make `Ligand.to_oemol()` or `sdf_string_to_oemol` do that.

Incidentally, this is the cause of all these warnings:
`Warning: OECreateInChI: InChI only supports molecules with between 1 and 1023 atoms! (note: large molecule support is experimental)`

https://gist.github.com/apayne97/8d2c8a13f6045ad5da3bea13d04aa262

**Comment by apayne97** [comment]
Looks like this was address in #1000 #1001
